# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_schedule', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pricing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_schedule.MoviePricing'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket',
            field=models.ManyToManyField(to='movie_schedule.CinemaSeat'),
        ),
    ]
