# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_schedule', '0005_auto_20160515_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_payment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
