# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_schedule', '0007_auto_20160515_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_schedule.Movie'),
        ),
    ]
