# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_schedule', '0015_auto_20160515_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 15, 21, 58, 52, 406769, tzinfo=utc)),
        ),
    ]
