# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie_schedule', '0017_auto_20160515_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 16, 16, 52, 58, 459532, tzinfo=utc)),
        ),
    ]
